stages:
  - build
  - test
  - deploy

variables:
  BUILD_CONFIGURATION: "Release"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build Api/Api.csproj -c $BUILD_CONFIGURATION
  artifacts:
    paths:
      - bin/

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet test Api/Api.csproj --no-build
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:20.10.7
  services:
    - docker:dind
  script:
    - docker build -t my-app:latest .
    - docker run -d -p 8080:8080 my-app:latest
  only:
    - main
